#pragma once

#include "glcorearb.h"

int LoadGL();

extern PFNGLACTIVESHADERPROGRAMPROC							__glActiveShaderProgram;
extern PFNGLACTIVETEXTUREPROC								__glActiveTexture;
extern PFNGLATTACHSHADERPROC								__glAttachShader;
extern PFNGLBEGINCONDITIONALRENDERPROC						__glBeginConditionalRender;
extern PFNGLBEGINQUERYPROC									__glBeginQuery;
extern PFNGLBEGINQUERYINDEXEDPROC							__glBeginQueryIndexed;
extern PFNGLBEGINTRANSFORMFEEDBACKPROC						__glBeginTransformFeedback;
extern PFNGLBINDATTRIBLOCATIONPROC							__glBindAttribLocation;
extern PFNGLBINDBUFFERPROC									__glBindBuffer;
extern PFNGLBINDBUFFERBASEPROC								__glBindBufferBase;
extern PFNGLBINDBUFFERRANGEPROC								__glBindBufferRange;
extern PFNGLBINDBUFFERSBASEPROC								__glBindBuffersBase;
extern PFNGLBINDBUFFERSRANGEPROC							__glBindBuffersRange;
extern PFNGLBINDFRAGDATALOCATIONPROC						__glBindFragDataLocation;
extern PFNGLBINDFRAGDATALOCATIONINDEXEDPROC					__glBindFragDataLocationIndexed;
extern PFNGLBINDFRAMEBUFFERPROC								__glBindFramebuffer;
extern PFNGLBINDIMAGETEXTUREPROC							__glBindImageTexture;
extern PFNGLBINDIMAGETEXTURESPROC							__glBindImageTextures;
extern PFNGLBINDPROGRAMPIPELINEPROC							__glBindProgramPipeline;
extern PFNGLBINDRENDERBUFFERPROC							__glBindRenderbuffer;
extern PFNGLBINDSAMPLERPROC									__glBindSampler;
extern PFNGLBINDSAMPLERSPROC								__glBindSamplers;
extern PFNGLBINDTEXTUREPROC									__glBindTexture;
extern PFNGLBINDTEXTUREUNITPROC								__glBindTextureUnit;
extern PFNGLBINDTEXTURESPROC								__glBindTextures;
extern PFNGLBINDTRANSFORMFEEDBACKPROC						__glBindTransformFeedback;
extern PFNGLBINDVERTEXARRAYPROC								__glBindVertexArray;
extern PFNGLBINDVERTEXBUFFERPROC							__glBindVertexBuffer;
extern PFNGLBINDVERTEXBUFFERSPROC							__glBindVertexBuffers;
extern PFNGLBLENDCOLORPROC									__glBlendColor;
extern PFNGLBLENDEQUATIONPROC								__glBlendEquation;
extern PFNGLBLENDEQUATIONSEPARATEPROC						__glBlendEquationSeparate;
extern PFNGLBLENDEQUATIONSEPARATEIPROC						__glBlendEquationSeparatei;
extern PFNGLBLENDEQUATIONIPROC								__glBlendEquationi;
extern PFNGLBLENDFUNCPROC									__glBlendFunc;
extern PFNGLBLENDFUNCSEPARATEPROC							__glBlendFuncSeparate;
extern PFNGLBLENDFUNCSEPARATEIPROC							__glBlendFuncSeparatei;
extern PFNGLBLENDFUNCIPROC									__glBlendFunci;
extern PFNGLBLITFRAMEBUFFERPROC								__glBlitFramebuffer;
extern PFNGLBLITNAMEDFRAMEBUFFERPROC						__glBlitNamedFramebuffer;
extern PFNGLBUFFERDATAPROC									__glBufferData;
extern PFNGLBUFFERSTORAGEPROC								__glBufferStorage;
extern PFNGLBUFFERSUBDATAPROC								__glBufferSubData;
extern PFNGLCHECKFRAMEBUFFERSTATUSPROC						__glCheckFramebufferStatus;
extern PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC					__glCheckNamedFramebufferStatus;
extern PFNGLCLAMPCOLORPROC									__glClampColor;
extern PFNGLCLEARPROC										__glClear;
extern PFNGLCLEARBUFFERDATAPROC								__glClearBufferData;
extern PFNGLCLEARBUFFERSUBDATAPROC							__glClearBufferSubData;
extern PFNGLCLEARBUFFERFIPROC								__glClearBufferfi;
extern PFNGLCLEARBUFFERFVPROC								__glClearBufferfv;
extern PFNGLCLEARBUFFERIVPROC								__glClearBufferiv;
extern PFNGLCLEARBUFFERUIVPROC								__glClearBufferuiv;
extern PFNGLCLEARCOLORPROC									__glClearColor;
extern PFNGLCLEARDEPTHPROC									__glClearDepth;
extern PFNGLCLEARDEPTHFPROC									__glClearDepthf;
extern PFNGLCLEARNAMEDBUFFERDATAPROC						__glClearNamedBufferData;
extern PFNGLCLEARNAMEDBUFFERSUBDATAPROC						__glClearNamedBufferSubData;
extern PFNGLCLEARNAMEDFRAMEBUFFERFIPROC						__glClearNamedFramebufferfi;
extern PFNGLCLEARNAMEDFRAMEBUFFERFVPROC						__glClearNamedFramebufferfv;
extern PFNGLCLEARNAMEDFRAMEBUFFERIVPROC						__glClearNamedFramebufferiv;
extern PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC					__glClearNamedFramebufferuiv;
extern PFNGLCLEARSTENCILPROC								__glClearStencil;
extern PFNGLCLEARTEXIMAGEPROC								__glClearTexImage;
extern PFNGLCLEARTEXSUBIMAGEPROC							__glClearTexSubImage;
extern PFNGLCLIENTWAITSYNCPROC								__glClientWaitSync;
extern PFNGLCLIPCONTROLPROC									__glClipControl;
extern PFNGLCOLORMASKPROC									__glColorMask;
extern PFNGLCOLORMASKIPROC									__glColorMaski;
extern PFNGLCOMPILESHADERPROC								__glCompileShader;
extern PFNGLCOMPRESSEDTEXIMAGE1DPROC						__glCompressedTexImage1D;
extern PFNGLCOMPRESSEDTEXIMAGE2DPROC						__glCompressedTexImage2D;
extern PFNGLCOMPRESSEDTEXIMAGE3DPROC						__glCompressedTexImage3D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC						__glCompressedTexSubImage1D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC						__glCompressedTexSubImage2D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC						__glCompressedTexSubImage3D;
extern PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC					__glCompressedTextureSubImage1D;
extern PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC					__glCompressedTextureSubImage2D;
extern PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC					__glCompressedTextureSubImage3D;
extern PFNGLCOPYBUFFERSUBDATAPROC							__glCopyBufferSubData;
extern PFNGLCOPYIMAGESUBDATAPROC							__glCopyImageSubData;
extern PFNGLCOPYNAMEDBUFFERSUBDATAPROC						__glCopyNamedBufferSubData;
extern PFNGLCOPYTEXIMAGE1DPROC								__glCopyTexImage1D;
extern PFNGLCOPYTEXIMAGE2DPROC								__glCopyTexImage2D;
extern PFNGLCOPYTEXSUBIMAGE1DPROC							__glCopyTexSubImage1D;
extern PFNGLCOPYTEXSUBIMAGE2DPROC							__glCopyTexSubImage2D;
extern PFNGLCOPYTEXSUBIMAGE3DPROC							__glCopyTexSubImage3D;
extern PFNGLCOPYTEXTURESUBIMAGE1DPROC						__glCopyTextureSubImage1D;
extern PFNGLCOPYTEXTURESUBIMAGE2DPROC						__glCopyTextureSubImage2D;
extern PFNGLCOPYTEXTURESUBIMAGE3DPROC						__glCopyTextureSubImage3D;
extern PFNGLCREATEBUFFERSPROC								__glCreateBuffers;
extern PFNGLCREATEFRAMEBUFFERSPROC							__glCreateFramebuffers;
extern PFNGLCREATEPROGRAMPROC								__glCreateProgram;
extern PFNGLCREATEPROGRAMPIPELINESPROC						__glCreateProgramPipelines;
extern PFNGLCREATEQUERIESPROC								__glCreateQueries;
extern PFNGLCREATERENDERBUFFERSPROC							__glCreateRenderbuffers;
extern PFNGLCREATESAMPLERSPROC								__glCreateSamplers;
extern PFNGLCREATESHADERPROC								__glCreateShader;
extern PFNGLCREATESHADERPROGRAMVPROC						__glCreateShaderProgramv;
extern PFNGLCREATETEXTURESPROC								__glCreateTextures;
extern PFNGLCREATETRANSFORMFEEDBACKSPROC					__glCreateTransformFeedbacks;
extern PFNGLCREATEVERTEXARRAYSPROC							__glCreateVertexArrays;
extern PFNGLCULLFACEPROC									__glCullFace;
extern PFNGLDEBUGMESSAGECALLBACKPROC						__glDebugMessageCallback;
extern PFNGLDEBUGMESSAGECONTROLPROC							__glDebugMessageControl;
extern PFNGLDEBUGMESSAGEINSERTPROC							__glDebugMessageInsert;
extern PFNGLDELETEBUFFERSPROC								__glDeleteBuffers;
extern PFNGLDELETEFRAMEBUFFERSPROC							__glDeleteFramebuffers;
extern PFNGLDELETEPROGRAMPROC								__glDeleteProgram;
extern PFNGLDELETEPROGRAMPIPELINESPROC						__glDeleteProgramPipelines;
extern PFNGLDELETEQUERIESPROC								__glDeleteQueries;
extern PFNGLDELETERENDERBUFFERSPROC							__glDeleteRenderbuffers;
extern PFNGLDELETESAMPLERSPROC								__glDeleteSamplers;
extern PFNGLDELETESHADERPROC								__glDeleteShader;
extern PFNGLDELETESYNCPROC									__glDeleteSync;
extern PFNGLDELETETEXTURESPROC								__glDeleteTextures;
extern PFNGLDELETETRANSFORMFEEDBACKSPROC					__glDeleteTransformFeedbacks;
extern PFNGLDELETEVERTEXARRAYSPROC							__glDeleteVertexArrays;
extern PFNGLDEPTHFUNCPROC									__glDepthFunc;
extern PFNGLDEPTHMASKPROC									__glDepthMask;
extern PFNGLDEPTHRANGEPROC									__glDepthRange;
extern PFNGLDEPTHRANGEARRAYVPROC							__glDepthRangeArrayv;
extern PFNGLDEPTHRANGEINDEXEDPROC							__glDepthRangeIndexed;
extern PFNGLDEPTHRANGEFPROC									__glDepthRangef;
extern PFNGLDETACHSHADERPROC								__glDetachShader;
extern PFNGLDISABLEPROC										__glDisable;
extern PFNGLDISABLEVERTEXARRAYATTRIBPROC					__glDisableVertexArrayAttrib;
extern PFNGLDISABLEVERTEXATTRIBARRAYPROC					__glDisableVertexAttribArray;
extern PFNGLDISABLEIPROC									__glDisablei;
extern PFNGLDISPATCHCOMPUTEPROC								__glDispatchCompute;
extern PFNGLDISPATCHCOMPUTEINDIRECTPROC						__glDispatchComputeIndirect;
extern PFNGLDRAWARRAYSPROC									__glDrawArrays;
extern PFNGLDRAWARRAYSINDIRECTPROC							__glDrawArraysIndirect;
extern PFNGLDRAWARRAYSINSTANCEDPROC							__glDrawArraysInstanced;
extern PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC				__glDrawArraysInstancedBaseInstance;
extern PFNGLDRAWBUFFERPROC									__glDrawBuffer;
extern PFNGLDRAWBUFFERSPROC									__glDrawBuffers;
extern PFNGLDRAWELEMENTSPROC								__glDrawElements;
extern PFNGLDRAWELEMENTSBASEVERTEXPROC						__glDrawElementsBaseVertex;
extern PFNGLDRAWELEMENTSINDIRECTPROC						__glDrawElementsIndirect;
extern PFNGLDRAWELEMENTSINSTANCEDPROC						__glDrawElementsInstanced;
extern PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC			__glDrawElementsInstancedBaseInstance;
extern PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC				__glDrawElementsInstancedBaseVertex;
extern PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC	__glDrawElementsInstancedBaseVertexBaseInstance;
extern PFNGLDRAWRANGEELEMENTSPROC							__glDrawRangeElements;
extern PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC					__glDrawRangeElementsBaseVertex;
extern PFNGLDRAWTRANSFORMFEEDBACKPROC						__glDrawTransformFeedback;
extern PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC				__glDrawTransformFeedbackInstanced;
extern PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC					__glDrawTransformFeedbackStream;
extern PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC		__glDrawTransformFeedbackStreamInstanced;
extern PFNGLENABLEPROC										__glEnable;
extern PFNGLENABLEVERTEXARRAYATTRIBPROC						__glEnableVertexArrayAttrib;
extern PFNGLENABLEVERTEXATTRIBARRAYPROC						__glEnableVertexAttribArray;
extern PFNGLENABLEIPROC										__glEnablei;
extern PFNGLENDCONDITIONALRENDERPROC						__glEndConditionalRender;
extern PFNGLENDQUERYPROC									__glEndQuery;
extern PFNGLENDQUERYINDEXEDPROC								__glEndQueryIndexed;
extern PFNGLENDTRANSFORMFEEDBACKPROC						__glEndTransformFeedback;
extern PFNGLFENCESYNCPROC									__glFenceSync;
extern PFNGLFINISHPROC										__glFinish;
extern PFNGLFLUSHPROC										__glFlush;
extern PFNGLFLUSHMAPPEDBUFFERRANGEPROC						__glFlushMappedBufferRange;
extern PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC					__glFlushMappedNamedBufferRange;
extern PFNGLFRAMEBUFFERPARAMETERIPROC						__glFramebufferParameteri;
extern PFNGLFRAMEBUFFERPARAMETERIMESAPROC					__glFramebufferParameteriMESA;
extern PFNGLFRAMEBUFFERRENDERBUFFERPROC						__glFramebufferRenderbuffer;
extern PFNGLFRAMEBUFFERTEXTUREPROC							__glFramebufferTexture;
extern PFNGLFRAMEBUFFERTEXTURE1DPROC						__glFramebufferTexture1D;
extern PFNGLFRAMEBUFFERTEXTURE2DPROC						__glFramebufferTexture2D;
extern PFNGLFRAMEBUFFERTEXTURE3DPROC						__glFramebufferTexture3D;
extern PFNGLFRAMEBUFFERTEXTURELAYERPROC						__glFramebufferTextureLayer;
extern PFNGLFRONTFACEPROC									__glFrontFace;
extern PFNGLGENBUFFERSPROC									__glGenBuffers;
extern PFNGLGENFRAMEBUFFERSPROC								__glGenFramebuffers;
extern PFNGLGENPROGRAMPIPELINESPROC							__glGenProgramPipelines;
extern PFNGLGENQUERIESPROC									__glGenQueries;
extern PFNGLGENRENDERBUFFERSPROC							__glGenRenderbuffers;
extern PFNGLGENSAMPLERSPROC									__glGenSamplers;
extern PFNGLGENTEXTURESPROC									__glGenTextures;
extern PFNGLGENTRANSFORMFEEDBACKSPROC						__glGenTransformFeedbacks;
extern PFNGLGENVERTEXARRAYSPROC								__glGenVertexArrays;
extern PFNGLGENERATEMIPMAPPROC								__glGenerateMipmap;
extern PFNGLGENERATETEXTUREMIPMAPPROC						__glGenerateTextureMipmap;
extern PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC				__glGetActiveAtomicCounterBufferiv;
extern PFNGLGETACTIVEATTRIBPROC								__glGetActiveAttrib;
extern PFNGLGETACTIVESUBROUTINENAMEPROC						__glGetActiveSubroutineName;
extern PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC				__glGetActiveSubroutineUniformName;
extern PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC				__glGetActiveSubroutineUniformiv;
extern PFNGLGETACTIVEUNIFORMPROC							__glGetActiveUniform;
extern PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC					__glGetActiveUniformBlockName;
extern PFNGLGETACTIVEUNIFORMBLOCKIVPROC						__glGetActiveUniformBlockiv;
extern PFNGLGETACTIVEUNIFORMNAMEPROC						__glGetActiveUniformName;
extern PFNGLGETACTIVEUNIFORMSIVPROC							__glGetActiveUniformsiv;
extern PFNGLGETATTACHEDSHADERSPROC							__glGetAttachedShaders;
extern PFNGLGETATTRIBLOCATIONPROC							__glGetAttribLocation;
extern PFNGLGETBOOLEANI_VPROC								__glGetBooleani_v;
extern PFNGLGETBOOLEANVPROC									__glGetBooleanv;
extern PFNGLGETBUFFERPARAMETERI64VPROC						__glGetBufferParameteri64v;
extern PFNGLGETBUFFERPARAMETERIVPROC						__glGetBufferParameteriv;
extern PFNGLGETBUFFERPOINTERVPROC							__glGetBufferPointerv;
extern PFNGLGETBUFFERSUBDATAPROC							__glGetBufferSubData;
extern PFNGLGETCOMPRESSEDTEXIMAGEPROC						__glGetCompressedTexImage;
extern PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC					__glGetCompressedTextureImage;
extern PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC				__glGetCompressedTextureSubImage;
extern PFNGLGETDEBUGMESSAGELOGPROC							__glGetDebugMessageLog;
extern PFNGLGETDOUBLEI_VPROC								__glGetDoublei_v;
extern PFNGLGETDOUBLEVPROC									__glGetDoublev;
extern PFNGLGETERRORPROC									__glGetError;
extern PFNGLGETFLOATI_VPROC									__glGetFloati_v;
extern PFNGLGETFLOATVPROC									__glGetFloatv;
extern PFNGLGETFRAGDATAINDEXPROC							__glGetFragDataIndex;
extern PFNGLGETFRAGDATALOCATIONPROC							__glGetFragDataLocation;
extern PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC			__glGetFramebufferAttachmentParameteriv;
extern PFNGLGETFRAMEBUFFERPARAMETERIVPROC					__glGetFramebufferParameteriv;
extern PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC				__glGetFramebufferParameterivMESA;
extern PFNGLGETGRAPHICSRESETSTATUSPROC						__glGetGraphicsResetStatus;
extern PFNGLGETINTEGER64I_VPROC								__glGetInteger64i_v;
extern PFNGLGETINTEGER64VPROC								__glGetInteger64v;
extern PFNGLGETINTEGERI_VPROC								__glGetIntegeri_v;
extern PFNGLGETINTEGERVPROC									__glGetIntegerv;
extern PFNGLGETINTERNALFORMATI64VPROC						__glGetInternalformati64v;
extern PFNGLGETINTERNALFORMATIVPROC							__glGetInternalformativ;
extern PFNGLGETMULTISAMPLEFVPROC							__glGetMultisamplefv;
extern PFNGLGETNAMEDBUFFERPARAMETERI64VPROC					__glGetNamedBufferParameteri64v;
extern PFNGLGETNAMEDBUFFERPARAMETERIVPROC					__glGetNamedBufferParameteriv;
extern PFNGLGETNAMEDBUFFERPOINTERVPROC						__glGetNamedBufferPointerv;
extern PFNGLGETNAMEDBUFFERSUBDATAPROC						__glGetNamedBufferSubData;
extern PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC	__glGetNamedFramebufferAttachmentParameteriv;
extern PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC				__glGetNamedFramebufferParameteriv;
extern PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC				__glGetNamedRenderbufferParameteriv;
extern PFNGLGETOBJECTLABELPROC								__glGetObjectLabel;
extern PFNGLGETOBJECTPTRLABELPROC							__glGetObjectPtrLabel;
extern PFNGLGETPOINTERVPROC									__glGetPointerv;
extern PFNGLGETPROGRAMBINARYPROC							__glGetProgramBinary;
extern PFNGLGETPROGRAMINFOLOGPROC							__glGetProgramInfoLog;
extern PFNGLGETPROGRAMINTERFACEIVPROC						__glGetProgramInterfaceiv;
extern PFNGLGETPROGRAMPIPELINEINFOLOGPROC					__glGetProgramPipelineInfoLog;
extern PFNGLGETPROGRAMPIPELINEIVPROC						__glGetProgramPipelineiv;
extern PFNGLGETPROGRAMRESOURCEINDEXPROC						__glGetProgramResourceIndex;
extern PFNGLGETPROGRAMRESOURCELOCATIONPROC					__glGetProgramResourceLocation;
extern PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC				__glGetProgramResourceLocationIndex;
extern PFNGLGETPROGRAMRESOURCENAMEPROC						__glGetProgramResourceName;
extern PFNGLGETPROGRAMRESOURCEIVPROC						__glGetProgramResourceiv;
extern PFNGLGETPROGRAMSTAGEIVPROC							__glGetProgramStageiv;
extern PFNGLGETPROGRAMIVPROC								__glGetProgramiv;
extern PFNGLGETQUERYBUFFEROBJECTI64VPROC					__glGetQueryBufferObjecti64v;
extern PFNGLGETQUERYBUFFEROBJECTIVPROC						__glGetQueryBufferObjectiv;
extern PFNGLGETQUERYBUFFEROBJECTUI64VPROC					__glGetQueryBufferObjectui64v;
extern PFNGLGETQUERYBUFFEROBJECTUIVPROC						__glGetQueryBufferObjectuiv;
extern PFNGLGETQUERYINDEXEDIVPROC							__glGetQueryIndexediv;
extern PFNGLGETQUERYOBJECTI64VPROC							__glGetQueryObjecti64v;
extern PFNGLGETQUERYOBJECTIVPROC							__glGetQueryObjectiv;
extern PFNGLGETQUERYOBJECTUI64VPROC							__glGetQueryObjectui64v;
extern PFNGLGETQUERYOBJECTUIVPROC							__glGetQueryObjectuiv;
extern PFNGLGETQUERYIVPROC									__glGetQueryiv;
extern PFNGLGETRENDERBUFFERPARAMETERIVPROC					__glGetRenderbufferParameteriv;
extern PFNGLGETSAMPLERPARAMETERIIVPROC						__glGetSamplerParameterIiv;
extern PFNGLGETSAMPLERPARAMETERIUIVPROC						__glGetSamplerParameterIuiv;
extern PFNGLGETSAMPLERPARAMETERFVPROC						__glGetSamplerParameterfv;
extern PFNGLGETSAMPLERPARAMETERIVPROC						__glGetSamplerParameteriv;
extern PFNGLGETSHADERINFOLOGPROC							__glGetShaderInfoLog;
extern PFNGLGETSHADERPRECISIONFORMATPROC					__glGetShaderPrecisionFormat;
extern PFNGLGETSHADERSOURCEPROC								__glGetShaderSource;
extern PFNGLGETSHADERIVPROC									__glGetShaderiv;
extern PFNGLGETSTRINGPROC									__glGetString;
extern PFNGLGETSTRINGIPROC									__glGetStringi;
extern PFNGLGETSUBROUTINEINDEXPROC							__glGetSubroutineIndex;
extern PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC				__glGetSubroutineUniformLocation;
extern PFNGLGETSYNCIVPROC									__glGetSynciv;
extern PFNGLGETTEXIMAGEPROC									__glGetTexImage;
extern PFNGLGETTEXLEVELPARAMETERFVPROC						__glGetTexLevelParameterfv;
extern PFNGLGETTEXLEVELPARAMETERIVPROC						__glGetTexLevelParameteriv;
extern PFNGLGETTEXPARAMETERIIVPROC							__glGetTexParameterIiv;
extern PFNGLGETTEXPARAMETERIUIVPROC							__glGetTexParameterIuiv;
extern PFNGLGETTEXPARAMETERFVPROC							__glGetTexParameterfv;
extern PFNGLGETTEXPARAMETERIVPROC							__glGetTexParameteriv;
extern PFNGLGETTEXTUREIMAGEPROC								__glGetTextureImage;
extern PFNGLGETTEXTURELEVELPARAMETERFVPROC					__glGetTextureLevelParameterfv;
extern PFNGLGETTEXTURELEVELPARAMETERIVPROC					__glGetTextureLevelParameteriv;
extern PFNGLGETTEXTUREPARAMETERIIVPROC						__glGetTextureParameterIiv;
extern PFNGLGETTEXTUREPARAMETERIUIVPROC						__glGetTextureParameterIuiv;
extern PFNGLGETTEXTUREPARAMETERFVPROC						__glGetTextureParameterfv;
extern PFNGLGETTEXTUREPARAMETERIVPROC						__glGetTextureParameteriv;
extern PFNGLGETTEXTURESUBIMAGEPROC							__glGetTextureSubImage;
extern PFNGLGETTRANSFORMFEEDBACKVARYINGPROC					__glGetTransformFeedbackVarying;
extern PFNGLGETTRANSFORMFEEDBACKI64_VPROC					__glGetTransformFeedbacki64_v;
extern PFNGLGETTRANSFORMFEEDBACKI_VPROC						__glGetTransformFeedbacki_v;
extern PFNGLGETTRANSFORMFEEDBACKIVPROC						__glGetTransformFeedbackiv;
extern PFNGLGETUNIFORMBLOCKINDEXPROC						__glGetUniformBlockIndex;
extern PFNGLGETUNIFORMINDICESPROC							__glGetUniformIndices;
extern PFNGLGETUNIFORMLOCATIONPROC							__glGetUniformLocation;
extern PFNGLGETUNIFORMSUBROUTINEUIVPROC						__glGetUniformSubroutineuiv;
extern PFNGLGETUNIFORMDVPROC								__glGetUniformdv;
extern PFNGLGETUNIFORMFVPROC								__glGetUniformfv;
extern PFNGLGETUNIFORMIVPROC								__glGetUniformiv;
extern PFNGLGETUNIFORMUIVPROC								__glGetUniformuiv;
extern PFNGLGETVERTEXARRAYINDEXED64IVPROC					__glGetVertexArrayIndexed64iv;
extern PFNGLGETVERTEXARRAYINDEXEDIVPROC						__glGetVertexArrayIndexediv;
extern PFNGLGETVERTEXARRAYIVPROC							__glGetVertexArrayiv;
extern PFNGLGETVERTEXATTRIBIIVPROC							__glGetVertexAttribIiv;
extern PFNGLGETVERTEXATTRIBIUIVPROC							__glGetVertexAttribIuiv;
extern PFNGLGETVERTEXATTRIBLDVPROC							__glGetVertexAttribLdv;
extern PFNGLGETVERTEXATTRIBPOINTERVPROC						__glGetVertexAttribPointerv;
extern PFNGLGETVERTEXATTRIBDVPROC							__glGetVertexAttribdv;
extern PFNGLGETVERTEXATTRIBFVPROC							__glGetVertexAttribfv;
extern PFNGLGETVERTEXATTRIBIVPROC							__glGetVertexAttribiv;
extern PFNGLGETNCOMPRESSEDTEXIMAGEPROC						__glGetnCompressedTexImage;
extern PFNGLGETNTEXIMAGEPROC								__glGetnTexImage;
extern PFNGLGETNUNIFORMDVPROC								__glGetnUniformdv;
extern PFNGLGETNUNIFORMFVPROC								__glGetnUniformfv;
extern PFNGLGETNUNIFORMIVPROC								__glGetnUniformiv;
extern PFNGLGETNUNIFORMUIVPROC								__glGetnUniformuiv;
extern PFNGLHINTPROC										__glHint;
extern PFNGLINVALIDATEBUFFERDATAPROC						__glInvalidateBufferData;
extern PFNGLINVALIDATEBUFFERSUBDATAPROC						__glInvalidateBufferSubData;
extern PFNGLINVALIDATEFRAMEBUFFERPROC						__glInvalidateFramebuffer;
extern PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC				__glInvalidateNamedFramebufferData;
extern PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC			__glInvalidateNamedFramebufferSubData;
extern PFNGLINVALIDATESUBFRAMEBUFFERPROC					__glInvalidateSubFramebuffer;
extern PFNGLINVALIDATETEXIMAGEPROC							__glInvalidateTexImage;
extern PFNGLINVALIDATETEXSUBIMAGEPROC						__glInvalidateTexSubImage;
extern PFNGLISBUFFERPROC									__glIsBuffer;
extern PFNGLISENABLEDPROC									__glIsEnabled;
extern PFNGLISENABLEDIPROC									__glIsEnabledi;
extern PFNGLISFRAMEBUFFERPROC								__glIsFramebuffer;
extern PFNGLISPROGRAMPROC									__glIsProgram;
extern PFNGLISPROGRAMPIPELINEPROC							__glIsProgramPipeline;
extern PFNGLISQUERYPROC										__glIsQuery;
extern PFNGLISRENDERBUFFERPROC								__glIsRenderbuffer;
extern PFNGLISSAMPLERPROC									__glIsSampler;
extern PFNGLISSHADERPROC									__glIsShader;
extern PFNGLISSYNCPROC										__glIsSync;
extern PFNGLISTEXTUREPROC									__glIsTexture;
extern PFNGLISTRANSFORMFEEDBACKPROC							__glIsTransformFeedback;
extern PFNGLISVERTEXARRAYPROC								__glIsVertexArray;
extern PFNGLLINEWIDTHPROC									__glLineWidth;
extern PFNGLLINKPROGRAMPROC									__glLinkProgram;
extern PFNGLLOGICOPPROC										__glLogicOp;
extern PFNGLMAPBUFFERPROC									__glMapBuffer;
extern PFNGLMAPBUFFERRANGEPROC								__glMapBufferRange;
extern PFNGLMAPNAMEDBUFFERPROC								__glMapNamedBuffer;
extern PFNGLMAPNAMEDBUFFERRANGEPROC							__glMapNamedBufferRange;
extern PFNGLMEMORYBARRIERPROC								__glMemoryBarrier;
extern PFNGLMEMORYBARRIERBYREGIONPROC						__glMemoryBarrierByRegion;
extern PFNGLMINSAMPLESHADINGPROC							__glMinSampleShading;
extern PFNGLMULTIDRAWARRAYSPROC								__glMultiDrawArrays;
extern PFNGLMULTIDRAWARRAYSINDIRECTPROC						__glMultiDrawArraysIndirect;
extern PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC				__glMultiDrawArraysIndirectCount;
extern PFNGLMULTIDRAWELEMENTSPROC							__glMultiDrawElements;
extern PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC					__glMultiDrawElementsBaseVertex;
extern PFNGLMULTIDRAWELEMENTSINDIRECTPROC					__glMultiDrawElementsIndirect;
extern PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC				__glMultiDrawElementsIndirectCount;
extern PFNGLNAMEDBUFFERDATAPROC								__glNamedBufferData;
extern PFNGLNAMEDBUFFERSTORAGEPROC							__glNamedBufferStorage;
extern PFNGLNAMEDBUFFERSUBDATAPROC							__glNamedBufferSubData;
extern PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC					__glNamedFramebufferDrawBuffer;
extern PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC					__glNamedFramebufferDrawBuffers;
extern PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC					__glNamedFramebufferParameteri;
extern PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC					__glNamedFramebufferReadBuffer;
extern PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC				__glNamedFramebufferRenderbuffer;
extern PFNGLNAMEDFRAMEBUFFERTEXTUREPROC						__glNamedFramebufferTexture;
extern PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC				__glNamedFramebufferTextureLayer;
extern PFNGLNAMEDRENDERBUFFERSTORAGEPROC					__glNamedRenderbufferStorage;
extern PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC			__glNamedRenderbufferStorageMultisample;
extern PFNGLOBJECTLABELPROC									__glObjectLabel;
extern PFNGLOBJECTPTRLABELPROC								__glObjectPtrLabel;
extern PFNGLPATCHPARAMETERFVPROC							__glPatchParameterfv;
extern PFNGLPATCHPARAMETERIPROC								__glPatchParameteri;
extern PFNGLPAUSETRANSFORMFEEDBACKPROC						__glPauseTransformFeedback;
extern PFNGLPIXELSTOREFPROC									__glPixelStoref;
extern PFNGLPIXELSTOREIPROC									__glPixelStorei;
extern PFNGLPOINTPARAMETERFPROC								__glPointParameterf;
extern PFNGLPOINTPARAMETERFVPROC							__glPointParameterfv;
extern PFNGLPOINTPARAMETERIPROC								__glPointParameteri;
extern PFNGLPOINTPARAMETERIVPROC							__glPointParameteriv;
extern PFNGLPOINTSIZEPROC									__glPointSize;
extern PFNGLPOLYGONMODEPROC									__glPolygonMode;
extern PFNGLPOLYGONOFFSETPROC								__glPolygonOffset;
extern PFNGLPOLYGONOFFSETCLAMPPROC							__glPolygonOffsetClamp;
extern PFNGLPOPDEBUGGROUPPROC								__glPopDebugGroup;
extern PFNGLPRIMITIVERESTARTINDEXPROC						__glPrimitiveRestartIndex;
extern PFNGLPROGRAMBINARYPROC								__glProgramBinary;
extern PFNGLPROGRAMPARAMETERIPROC							__glProgramParameteri;
extern PFNGLPROGRAMUNIFORM1DPROC							__glProgramUniform1d;
extern PFNGLPROGRAMUNIFORM1DVPROC							__glProgramUniform1dv;
extern PFNGLPROGRAMUNIFORM1FPROC							__glProgramUniform1f;
extern PFNGLPROGRAMUNIFORM1FVPROC							__glProgramUniform1fv;
extern PFNGLPROGRAMUNIFORM1IPROC							__glProgramUniform1i;
extern PFNGLPROGRAMUNIFORM1IVPROC							__glProgramUniform1iv;
extern PFNGLPROGRAMUNIFORM1UIPROC							__glProgramUniform1ui;
extern PFNGLPROGRAMUNIFORM1UIVPROC							__glProgramUniform1uiv;
extern PFNGLPROGRAMUNIFORM2DPROC							__glProgramUniform2d;
extern PFNGLPROGRAMUNIFORM2DVPROC							__glProgramUniform2dv;
extern PFNGLPROGRAMUNIFORM2FPROC							__glProgramUniform2f;
extern PFNGLPROGRAMUNIFORM2FVPROC							__glProgramUniform2fv;
extern PFNGLPROGRAMUNIFORM2IPROC							__glProgramUniform2i;
extern PFNGLPROGRAMUNIFORM2IVPROC							__glProgramUniform2iv;
extern PFNGLPROGRAMUNIFORM2UIPROC							__glProgramUniform2ui;
extern PFNGLPROGRAMUNIFORM2UIVPROC							__glProgramUniform2uiv;
extern PFNGLPROGRAMUNIFORM3DPROC							__glProgramUniform3d;
extern PFNGLPROGRAMUNIFORM3DVPROC							__glProgramUniform3dv;
extern PFNGLPROGRAMUNIFORM3FPROC							__glProgramUniform3f;
extern PFNGLPROGRAMUNIFORM3FVPROC							__glProgramUniform3fv;
extern PFNGLPROGRAMUNIFORM3IPROC							__glProgramUniform3i;
extern PFNGLPROGRAMUNIFORM3IVPROC							__glProgramUniform3iv;
extern PFNGLPROGRAMUNIFORM3UIPROC							__glProgramUniform3ui;
extern PFNGLPROGRAMUNIFORM3UIVPROC							__glProgramUniform3uiv;
extern PFNGLPROGRAMUNIFORM4DPROC							__glProgramUniform4d;
extern PFNGLPROGRAMUNIFORM4DVPROC							__glProgramUniform4dv;
extern PFNGLPROGRAMUNIFORM4FPROC							__glProgramUniform4f;
extern PFNGLPROGRAMUNIFORM4FVPROC							__glProgramUniform4fv;
extern PFNGLPROGRAMUNIFORM4IPROC							__glProgramUniform4i;
extern PFNGLPROGRAMUNIFORM4IVPROC							__glProgramUniform4iv;
extern PFNGLPROGRAMUNIFORM4UIPROC							__glProgramUniform4ui;
extern PFNGLPROGRAMUNIFORM4UIVPROC							__glProgramUniform4uiv;
extern PFNGLPROGRAMUNIFORMMATRIX2DVPROC						__glProgramUniformMatrix2dv;
extern PFNGLPROGRAMUNIFORMMATRIX2FVPROC						__glProgramUniformMatrix2fv;
extern PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC					__glProgramUniformMatrix2x3dv;
extern PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC					__glProgramUniformMatrix2x3fv;
extern PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC					__glProgramUniformMatrix2x4dv;
extern PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC					__glProgramUniformMatrix2x4fv;
extern PFNGLPROGRAMUNIFORMMATRIX3DVPROC						__glProgramUniformMatrix3dv;
extern PFNGLPROGRAMUNIFORMMATRIX3FVPROC						__glProgramUniformMatrix3fv;
extern PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC					__glProgramUniformMatrix3x2dv;
extern PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC					__glProgramUniformMatrix3x2fv;
extern PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC					__glProgramUniformMatrix3x4dv;
extern PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC					__glProgramUniformMatrix3x4fv;
extern PFNGLPROGRAMUNIFORMMATRIX4DVPROC						__glProgramUniformMatrix4dv;
extern PFNGLPROGRAMUNIFORMMATRIX4FVPROC						__glProgramUniformMatrix4fv;
extern PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC					__glProgramUniformMatrix4x2dv;
extern PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC					__glProgramUniformMatrix4x2fv;
extern PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC					__glProgramUniformMatrix4x3dv;
extern PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC					__glProgramUniformMatrix4x3fv;
extern PFNGLPROVOKINGVERTEXPROC								__glProvokingVertex;
extern PFNGLPUSHDEBUGGROUPPROC								__glPushDebugGroup;
extern PFNGLQUERYCOUNTERPROC								__glQueryCounter;
extern PFNGLREADBUFFERPROC									__glReadBuffer;
extern PFNGLREADPIXELSPROC									__glReadPixels;
extern PFNGLREADNPIXELSPROC									__glReadnPixels;
extern PFNGLRELEASESHADERCOMPILERPROC						__glReleaseShaderCompiler;
extern PFNGLRENDERBUFFERSTORAGEPROC							__glRenderbufferStorage;
extern PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC				__glRenderbufferStorageMultisample;
extern PFNGLRESUMETRANSFORMFEEDBACKPROC						__glResumeTransformFeedback;
extern PFNGLSAMPLECOVERAGEPROC								__glSampleCoverage;
extern PFNGLSAMPLEMASKIPROC									__glSampleMaski;
extern PFNGLSAMPLERPARAMETERIIVPROC							__glSamplerParameterIiv;
extern PFNGLSAMPLERPARAMETERIUIVPROC						__glSamplerParameterIuiv;
extern PFNGLSAMPLERPARAMETERFPROC							__glSamplerParameterf;
extern PFNGLSAMPLERPARAMETERFVPROC							__glSamplerParameterfv;
extern PFNGLSAMPLERPARAMETERIPROC							__glSamplerParameteri;
extern PFNGLSAMPLERPARAMETERIVPROC							__glSamplerParameteriv;
extern PFNGLSCISSORPROC										__glScissor;
extern PFNGLSCISSORARRAYVPROC								__glScissorArrayv;
extern PFNGLSCISSORINDEXEDPROC								__glScissorIndexed;
extern PFNGLSCISSORINDEXEDVPROC								__glScissorIndexedv;
extern PFNGLSHADERBINARYPROC								__glShaderBinary;
extern PFNGLSHADERSOURCEPROC								__glShaderSource;
extern PFNGLSHADERSTORAGEBLOCKBINDINGPROC					__glShaderStorageBlockBinding;
extern PFNGLSPECIALIZESHADERPROC							__glSpecializeShader;
extern PFNGLSTENCILFUNCPROC									__glStencilFunc;
extern PFNGLSTENCILFUNCSEPARATEPROC							__glStencilFuncSeparate;
extern PFNGLSTENCILMASKPROC									__glStencilMask;
extern PFNGLSTENCILMASKSEPARATEPROC							__glStencilMaskSeparate;
extern PFNGLSTENCILOPPROC									__glStencilOp;
extern PFNGLSTENCILOPSEPARATEPROC							__glStencilOpSeparate;
extern PFNGLTEXBUFFERPROC									__glTexBuffer;
extern PFNGLTEXBUFFERRANGEPROC								__glTexBufferRange;
extern PFNGLTEXIMAGE1DPROC									__glTexImage1D;
extern PFNGLTEXIMAGE2DPROC									__glTexImage2D;
extern PFNGLTEXIMAGE2DMULTISAMPLEPROC						__glTexImage2DMultisample;
extern PFNGLTEXIMAGE3DPROC									__glTexImage3D;
extern PFNGLTEXIMAGE3DMULTISAMPLEPROC						__glTexImage3DMultisample;
extern PFNGLTEXPARAMETERIIVPROC								__glTexParameterIiv;
extern PFNGLTEXPARAMETERIUIVPROC							__glTexParameterIuiv;
extern PFNGLTEXPARAMETERFPROC								__glTexParameterf;
extern PFNGLTEXPARAMETERFVPROC								__glTexParameterfv;
extern PFNGLTEXPARAMETERIPROC								__glTexParameteri;
extern PFNGLTEXPARAMETERIVPROC								__glTexParameteriv;
extern PFNGLTEXSTORAGE1DPROC								__glTexStorage1D;
extern PFNGLTEXSTORAGE2DPROC								__glTexStorage2D;
extern PFNGLTEXSTORAGE2DMULTISAMPLEPROC						__glTexStorage2DMultisample;
extern PFNGLTEXSTORAGE3DPROC								__glTexStorage3D;
extern PFNGLTEXSTORAGE3DMULTISAMPLEPROC						__glTexStorage3DMultisample;
extern PFNGLTEXSUBIMAGE1DPROC								__glTexSubImage1D;
extern PFNGLTEXSUBIMAGE2DPROC								__glTexSubImage2D;
extern PFNGLTEXSUBIMAGE3DPROC								__glTexSubImage3D;
extern PFNGLTEXTUREBARRIERPROC								__glTextureBarrier;
extern PFNGLTEXTUREBUFFERPROC								__glTextureBuffer;
extern PFNGLTEXTUREBUFFERRANGEPROC							__glTextureBufferRange;
extern PFNGLTEXTUREPARAMETERIIVPROC							__glTextureParameterIiv;
extern PFNGLTEXTUREPARAMETERIUIVPROC						__glTextureParameterIuiv;
extern PFNGLTEXTUREPARAMETERFPROC							__glTextureParameterf;
extern PFNGLTEXTUREPARAMETERFVPROC							__glTextureParameterfv;
extern PFNGLTEXTUREPARAMETERIPROC							__glTextureParameteri;
extern PFNGLTEXTUREPARAMETERIVPROC							__glTextureParameteriv;
extern PFNGLTEXTURESTORAGE1DPROC							__glTextureStorage1D;
extern PFNGLTEXTURESTORAGE2DPROC							__glTextureStorage2D;
extern PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC					__glTextureStorage2DMultisample;
extern PFNGLTEXTURESTORAGE3DPROC							__glTextureStorage3D;
extern PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC					__glTextureStorage3DMultisample;
extern PFNGLTEXTURESUBIMAGE1DPROC							__glTextureSubImage1D;
extern PFNGLTEXTURESUBIMAGE2DPROC							__glTextureSubImage2D;
extern PFNGLTEXTURESUBIMAGE3DPROC							__glTextureSubImage3D;
extern PFNGLTEXTUREVIEWPROC									__glTextureView;
extern PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC					__glTransformFeedbackBufferBase;
extern PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC				__glTransformFeedbackBufferRange;
extern PFNGLTRANSFORMFEEDBACKVARYINGSPROC					__glTransformFeedbackVaryings;
extern PFNGLUNIFORM1DPROC									__glUniform1d;
extern PFNGLUNIFORM1DVPROC									__glUniform1dv;
extern PFNGLUNIFORM1FPROC									__glUniform1f;
extern PFNGLUNIFORM1FVPROC									__glUniform1fv;
extern PFNGLUNIFORM1IPROC									__glUniform1i;
extern PFNGLUNIFORM1IVPROC									__glUniform1iv;
extern PFNGLUNIFORM1UIPROC									__glUniform1ui;
extern PFNGLUNIFORM1UIVPROC									__glUniform1uiv;
extern PFNGLUNIFORM2DPROC									__glUniform2d;
extern PFNGLUNIFORM2DVPROC									__glUniform2dv;
extern PFNGLUNIFORM2FPROC									__glUniform2f;
extern PFNGLUNIFORM2FVPROC									__glUniform2fv;
extern PFNGLUNIFORM2IPROC									__glUniform2i;
extern PFNGLUNIFORM2IVPROC									__glUniform2iv;
extern PFNGLUNIFORM2UIPROC									__glUniform2ui;
extern PFNGLUNIFORM2UIVPROC									__glUniform2uiv;
extern PFNGLUNIFORM3DPROC									__glUniform3d;
extern PFNGLUNIFORM3DVPROC									__glUniform3dv;
extern PFNGLUNIFORM3FPROC									__glUniform3f;
extern PFNGLUNIFORM3FVPROC									__glUniform3fv;
extern PFNGLUNIFORM3IPROC									__glUniform3i;
extern PFNGLUNIFORM3IVPROC									__glUniform3iv;
extern PFNGLUNIFORM3UIPROC									__glUniform3ui;
extern PFNGLUNIFORM3UIVPROC									__glUniform3uiv;
extern PFNGLUNIFORM4DPROC									__glUniform4d;
extern PFNGLUNIFORM4DVPROC									__glUniform4dv;
extern PFNGLUNIFORM4FPROC									__glUniform4f;
extern PFNGLUNIFORM4FVPROC									__glUniform4fv;
extern PFNGLUNIFORM4IPROC									__glUniform4i;
extern PFNGLUNIFORM4IVPROC									__glUniform4iv;
extern PFNGLUNIFORM4UIPROC									__glUniform4ui;
extern PFNGLUNIFORM4UIVPROC									__glUniform4uiv;
extern PFNGLUNIFORMBLOCKBINDINGPROC							__glUniformBlockBinding;
extern PFNGLUNIFORMMATRIX2DVPROC							__glUniformMatrix2dv;
extern PFNGLUNIFORMMATRIX2FVPROC							__glUniformMatrix2fv;
extern PFNGLUNIFORMMATRIX2X3DVPROC							__glUniformMatrix2x3dv;
extern PFNGLUNIFORMMATRIX2X3FVPROC							__glUniformMatrix2x3fv;
extern PFNGLUNIFORMMATRIX2X4DVPROC							__glUniformMatrix2x4dv;
extern PFNGLUNIFORMMATRIX2X4FVPROC							__glUniformMatrix2x4fv;
extern PFNGLUNIFORMMATRIX3DVPROC							__glUniformMatrix3dv;
extern PFNGLUNIFORMMATRIX3FVPROC							__glUniformMatrix3fv;
extern PFNGLUNIFORMMATRIX3X2DVPROC							__glUniformMatrix3x2dv;
extern PFNGLUNIFORMMATRIX3X2FVPROC							__glUniformMatrix3x2fv;
extern PFNGLUNIFORMMATRIX3X4DVPROC							__glUniformMatrix3x4dv;
extern PFNGLUNIFORMMATRIX3X4FVPROC							__glUniformMatrix3x4fv;
extern PFNGLUNIFORMMATRIX4DVPROC							__glUniformMatrix4dv;
extern PFNGLUNIFORMMATRIX4FVPROC							__glUniformMatrix4fv;
extern PFNGLUNIFORMMATRIX4X2DVPROC							__glUniformMatrix4x2dv;
extern PFNGLUNIFORMMATRIX4X2FVPROC							__glUniformMatrix4x2fv;
extern PFNGLUNIFORMMATRIX4X3DVPROC							__glUniformMatrix4x3dv;
extern PFNGLUNIFORMMATRIX4X3FVPROC							__glUniformMatrix4x3fv;
extern PFNGLUNIFORMSUBROUTINESUIVPROC						__glUniformSubroutinesuiv;
extern PFNGLUNMAPBUFFERPROC									__glUnmapBuffer;
extern PFNGLUNMAPNAMEDBUFFERPROC							__glUnmapNamedBuffer;
extern PFNGLUSEPROGRAMPROC									__glUseProgram;
extern PFNGLUSEPROGRAMSTAGESPROC							__glUseProgramStages;
extern PFNGLVALIDATEPROGRAMPROC								__glValidateProgram;
extern PFNGLVALIDATEPROGRAMPIPELINEPROC						__glValidateProgramPipeline;
extern PFNGLVERTEXARRAYATTRIBBINDINGPROC					__glVertexArrayAttribBinding;
extern PFNGLVERTEXARRAYATTRIBFORMATPROC						__glVertexArrayAttribFormat;
extern PFNGLVERTEXARRAYATTRIBIFORMATPROC					__glVertexArrayAttribIFormat;
extern PFNGLVERTEXARRAYATTRIBLFORMATPROC					__glVertexArrayAttribLFormat;
extern PFNGLVERTEXARRAYBINDINGDIVISORPROC					__glVertexArrayBindingDivisor;
extern PFNGLVERTEXARRAYELEMENTBUFFERPROC					__glVertexArrayElementBuffer;
extern PFNGLVERTEXARRAYVERTEXBUFFERPROC						__glVertexArrayVertexBuffer;
extern PFNGLVERTEXARRAYVERTEXBUFFERSPROC					__glVertexArrayVertexBuffers;
extern PFNGLVERTEXATTRIB1DPROC								__glVertexAttrib1d;
extern PFNGLVERTEXATTRIB1DVPROC								__glVertexAttrib1dv;
extern PFNGLVERTEXATTRIB1FPROC								__glVertexAttrib1f;
extern PFNGLVERTEXATTRIB1FVPROC								__glVertexAttrib1fv;
extern PFNGLVERTEXATTRIB1SPROC								__glVertexAttrib1s;
extern PFNGLVERTEXATTRIB1SVPROC								__glVertexAttrib1sv;
extern PFNGLVERTEXATTRIB2DPROC								__glVertexAttrib2d;
extern PFNGLVERTEXATTRIB2DVPROC								__glVertexAttrib2dv;
extern PFNGLVERTEXATTRIB2FPROC								__glVertexAttrib2f;
extern PFNGLVERTEXATTRIB2FVPROC								__glVertexAttrib2fv;
extern PFNGLVERTEXATTRIB2SPROC								__glVertexAttrib2s;
extern PFNGLVERTEXATTRIB2SVPROC								__glVertexAttrib2sv;
extern PFNGLVERTEXATTRIB3DPROC								__glVertexAttrib3d;
extern PFNGLVERTEXATTRIB3DVPROC								__glVertexAttrib3dv;
extern PFNGLVERTEXATTRIB3FPROC								__glVertexAttrib3f;
extern PFNGLVERTEXATTRIB3FVPROC								__glVertexAttrib3fv;
extern PFNGLVERTEXATTRIB3SPROC								__glVertexAttrib3s;
extern PFNGLVERTEXATTRIB3SVPROC								__glVertexAttrib3sv;
extern PFNGLVERTEXATTRIB4NBVPROC							__glVertexAttrib4Nbv;
extern PFNGLVERTEXATTRIB4NIVPROC							__glVertexAttrib4Niv;
extern PFNGLVERTEXATTRIB4NSVPROC							__glVertexAttrib4Nsv;
extern PFNGLVERTEXATTRIB4NUBPROC							__glVertexAttrib4Nub;
extern PFNGLVERTEXATTRIB4NUBVPROC							__glVertexAttrib4Nubv;
extern PFNGLVERTEXATTRIB4NUIVPROC							__glVertexAttrib4Nuiv;
extern PFNGLVERTEXATTRIB4NUSVPROC							__glVertexAttrib4Nusv;
extern PFNGLVERTEXATTRIB4BVPROC								__glVertexAttrib4bv;
extern PFNGLVERTEXATTRIB4DPROC								__glVertexAttrib4d;
extern PFNGLVERTEXATTRIB4DVPROC								__glVertexAttrib4dv;
extern PFNGLVERTEXATTRIB4FPROC								__glVertexAttrib4f;
extern PFNGLVERTEXATTRIB4FVPROC								__glVertexAttrib4fv;
extern PFNGLVERTEXATTRIB4IVPROC								__glVertexAttrib4iv;
extern PFNGLVERTEXATTRIB4SPROC								__glVertexAttrib4s;
extern PFNGLVERTEXATTRIB4SVPROC								__glVertexAttrib4sv;
extern PFNGLVERTEXATTRIB4UBVPROC							__glVertexAttrib4ubv;
extern PFNGLVERTEXATTRIB4UIVPROC							__glVertexAttrib4uiv;
extern PFNGLVERTEXATTRIB4USVPROC							__glVertexAttrib4usv;
extern PFNGLVERTEXATTRIBBINDINGPROC							__glVertexAttribBinding;
extern PFNGLVERTEXATTRIBDIVISORPROC							__glVertexAttribDivisor;
extern PFNGLVERTEXATTRIBFORMATPROC							__glVertexAttribFormat;
extern PFNGLVERTEXATTRIBI1IPROC								__glVertexAttribI1i;
extern PFNGLVERTEXATTRIBI1IVPROC							__glVertexAttribI1iv;
extern PFNGLVERTEXATTRIBI1UIPROC							__glVertexAttribI1ui;
extern PFNGLVERTEXATTRIBI1UIVPROC							__glVertexAttribI1uiv;
extern PFNGLVERTEXATTRIBI2IPROC								__glVertexAttribI2i;
extern PFNGLVERTEXATTRIBI2IVPROC							__glVertexAttribI2iv;
extern PFNGLVERTEXATTRIBI2UIPROC							__glVertexAttribI2ui;
extern PFNGLVERTEXATTRIBI2UIVPROC							__glVertexAttribI2uiv;
extern PFNGLVERTEXATTRIBI3IPROC								__glVertexAttribI3i;
extern PFNGLVERTEXATTRIBI3IVPROC							__glVertexAttribI3iv;
extern PFNGLVERTEXATTRIBI3UIPROC							__glVertexAttribI3ui;
extern PFNGLVERTEXATTRIBI3UIVPROC							__glVertexAttribI3uiv;
extern PFNGLVERTEXATTRIBI4BVPROC							__glVertexAttribI4bv;
extern PFNGLVERTEXATTRIBI4IPROC								__glVertexAttribI4i;
extern PFNGLVERTEXATTRIBI4IVPROC							__glVertexAttribI4iv;
extern PFNGLVERTEXATTRIBI4SVPROC							__glVertexAttribI4sv;
extern PFNGLVERTEXATTRIBI4UBVPROC							__glVertexAttribI4ubv;
extern PFNGLVERTEXATTRIBI4UIPROC							__glVertexAttribI4ui;
extern PFNGLVERTEXATTRIBI4UIVPROC							__glVertexAttribI4uiv;
extern PFNGLVERTEXATTRIBI4USVPROC							__glVertexAttribI4usv;
extern PFNGLVERTEXATTRIBIFORMATPROC							__glVertexAttribIFormat;
extern PFNGLVERTEXATTRIBIPOINTERPROC						__glVertexAttribIPointer;
extern PFNGLVERTEXATTRIBL1DPROC								__glVertexAttribL1d;
extern PFNGLVERTEXATTRIBL1DVPROC							__glVertexAttribL1dv;
extern PFNGLVERTEXATTRIBL2DPROC								__glVertexAttribL2d;
extern PFNGLVERTEXATTRIBL2DVPROC							__glVertexAttribL2dv;
extern PFNGLVERTEXATTRIBL3DPROC								__glVertexAttribL3d;
extern PFNGLVERTEXATTRIBL3DVPROC							__glVertexAttribL3dv;
extern PFNGLVERTEXATTRIBL4DPROC								__glVertexAttribL4d;
extern PFNGLVERTEXATTRIBL4DVPROC							__glVertexAttribL4dv;
extern PFNGLVERTEXATTRIBLFORMATPROC							__glVertexAttribLFormat;
extern PFNGLVERTEXATTRIBLPOINTERPROC						__glVertexAttribLPointer;
extern PFNGLVERTEXATTRIBP1UIPROC							__glVertexAttribP1ui;
extern PFNGLVERTEXATTRIBP1UIVPROC							__glVertexAttribP1uiv;
extern PFNGLVERTEXATTRIBP2UIPROC							__glVertexAttribP2ui;
extern PFNGLVERTEXATTRIBP2UIVPROC							__glVertexAttribP2uiv;
extern PFNGLVERTEXATTRIBP3UIPROC							__glVertexAttribP3ui;
extern PFNGLVERTEXATTRIBP3UIVPROC							__glVertexAttribP3uiv;
extern PFNGLVERTEXATTRIBP4UIPROC							__glVertexAttribP4ui;
extern PFNGLVERTEXATTRIBP4UIVPROC							__glVertexAttribP4uiv;
extern PFNGLVERTEXATTRIBPOINTERPROC							__glVertexAttribPointer;
extern PFNGLVERTEXBINDINGDIVISORPROC						__glVertexBindingDivisor;
extern PFNGLVIEWPORTPROC									__glViewport;
extern PFNGLVIEWPORTARRAYVPROC								__glViewportArrayv;
extern PFNGLVIEWPORTINDEXEDFPROC							__glViewportIndexedf;
extern PFNGLVIEWPORTINDEXEDFVPROC							__glViewportIndexedfv;
extern PFNGLWAITSYNCPROC									__glWaitSync;

#define glActiveShaderProgram							__glActiveShaderProgram
#define glActiveTexture									__glActiveTexture
#define glAttachShader									__glAttachShader
#define glBeginConditionalRender						__glBeginConditionalRender
#define glBeginQuery									__glBeginQuery
#define glBeginQueryIndexed								__glBeginQueryIndexed
#define glBeginTransformFeedback						__glBeginTransformFeedback
#define glBindAttribLocation							__glBindAttribLocation
#define glBindBuffer									__glBindBuffer
#define glBindBufferBase								__glBindBufferBase
#define glBindBufferRange								__glBindBufferRange
#define glBindBuffersBase								__glBindBuffersBase
#define glBindBuffersRange								__glBindBuffersRange
#define glBindFragDataLocation							__glBindFragDataLocation
#define glBindFragDataLocationIndexed					__glBindFragDataLocationIndexed
#define glBindFramebuffer								__glBindFramebuffer
#define glBindImageTexture								__glBindImageTexture
#define glBindImageTextures								__glBindImageTextures
#define glBindProgramPipeline							__glBindProgramPipeline
#define glBindRenderbuffer								__glBindRenderbuffer
#define glBindSampler									__glBindSampler
#define glBindSamplers									__glBindSamplers
#define glBindTexture									__glBindTexture
#define glBindTextureUnit								__glBindTextureUnit
#define glBindTextures									__glBindTextures
#define glBindTransformFeedback							__glBindTransformFeedback
#define glBindVertexArray								__glBindVertexArray
#define glBindVertexBuffer								__glBindVertexBuffer
#define glBindVertexBuffers								__glBindVertexBuffers
#define glBlendColor									__glBlendColor
#define glBlendEquation									__glBlendEquation
#define glBlendEquationSeparate							__glBlendEquationSeparate
#define glBlendEquationSeparatei						__glBlendEquationSeparatei
#define glBlendEquationi								__glBlendEquationi
#define glBlendFunc										__glBlendFunc
#define glBlendFuncSeparate								__glBlendFuncSeparate
#define glBlendFuncSeparatei							__glBlendFuncSeparatei
#define glBlendFunci									__glBlendFunci
#define glBlitFramebuffer								__glBlitFramebuffer
#define glBlitNamedFramebuffer							__glBlitNamedFramebuffer
#define glBufferData									__glBufferData
#define glBufferStorage									__glBufferStorage
#define glBufferSubData									__glBufferSubData
#define glCheckFramebufferStatus						__glCheckFramebufferStatus
#define glCheckNamedFramebufferStatus					__glCheckNamedFramebufferStatus
#define glClampColor									__glClampColor
#define glClear											__glClear
#define glClearBufferData								__glClearBufferData
#define glClearBufferSubData							__glClearBufferSubData
#define glClearBufferfi									__glClearBufferfi
#define glClearBufferfv									__glClearBufferfv
#define glClearBufferiv									__glClearBufferiv
#define glClearBufferuiv								__glClearBufferuiv
#define glClearColor									__glClearColor
#define glClearDepth									__glClearDepth
#define glClearDepthf									__glClearDepthf
#define glClearNamedBufferData							__glClearNamedBufferData
#define glClearNamedBufferSubData						__glClearNamedBufferSubData
#define glClearNamedFramebufferfi						__glClearNamedFramebufferfi
#define glClearNamedFramebufferfv						__glClearNamedFramebufferfv
#define glClearNamedFramebufferiv						__glClearNamedFramebufferiv
#define glClearNamedFramebufferuiv						__glClearNamedFramebufferuiv
#define glClearStencil									__glClearStencil
#define glClearTexImage									__glClearTexImage
#define glClearTexSubImage								__glClearTexSubImage
#define glClientWaitSync								__glClientWaitSync
#define glClipControl									__glClipControl
#define glColorMask										__glColorMask
#define glColorMaski									__glColorMaski
#define glCompileShader									__glCompileShader
#define glCompressedTexImage1D							__glCompressedTexImage1D
#define glCompressedTexImage2D							__glCompressedTexImage2D
#define glCompressedTexImage3D							__glCompressedTexImage3D
#define glCompressedTexSubImage1D						__glCompressedTexSubImage1D
#define glCompressedTexSubImage2D						__glCompressedTexSubImage2D
#define glCompressedTexSubImage3D						__glCompressedTexSubImage3D
#define glCompressedTextureSubImage1D					__glCompressedTextureSubImage1D
#define glCompressedTextureSubImage2D					__glCompressedTextureSubImage2D
#define glCompressedTextureSubImage3D					__glCompressedTextureSubImage3D
#define glCopyBufferSubData								__glCopyBufferSubData
#define glCopyImageSubData								__glCopyImageSubData
#define glCopyNamedBufferSubData						__glCopyNamedBufferSubData
#define glCopyTexImage1D								__glCopyTexImage1D
#define glCopyTexImage2D								__glCopyTexImage2D
#define glCopyTexSubImage1D								__glCopyTexSubImage1D
#define glCopyTexSubImage2D								__glCopyTexSubImage2D
#define glCopyTexSubImage3D								__glCopyTexSubImage3D
#define glCopyTextureSubImage1D							__glCopyTextureSubImage1D
#define glCopyTextureSubImage2D							__glCopyTextureSubImage2D
#define glCopyTextureSubImage3D							__glCopyTextureSubImage3D
#define glCreateBuffers									__glCreateBuffers
#define glCreateFramebuffers							__glCreateFramebuffers
#define glCreateProgram									__glCreateProgram
#define glCreateProgramPipelines						__glCreateProgramPipelines
#define glCreateQueries									__glCreateQueries
#define glCreateRenderbuffers							__glCreateRenderbuffers
#define glCreateSamplers								__glCreateSamplers
#define glCreateShader									__glCreateShader
#define glCreateShaderProgramv							__glCreateShaderProgramv
#define glCreateTextures								__glCreateTextures
#define glCreateTransformFeedbacks						__glCreateTransformFeedbacks
#define glCreateVertexArrays							__glCreateVertexArrays
#define glCullFace										__glCullFace
#define glDebugMessageCallback							__glDebugMessageCallback
#define glDebugMessageControl							__glDebugMessageControl
#define glDebugMessageInsert							__glDebugMessageInsert
#define glDeleteBuffers									__glDeleteBuffers
#define glDeleteFramebuffers							__glDeleteFramebuffers
#define glDeleteProgram									__glDeleteProgram
#define glDeleteProgramPipelines						__glDeleteProgramPipelines
#define glDeleteQueries									__glDeleteQueries
#define glDeleteRenderbuffers							__glDeleteRenderbuffers
#define glDeleteSamplers								__glDeleteSamplers
#define glDeleteShader									__glDeleteShader
#define glDeleteSync									__glDeleteSync
#define glDeleteTextures								__glDeleteTextures
#define glDeleteTransformFeedbacks						__glDeleteTransformFeedbacks
#define glDeleteVertexArrays							__glDeleteVertexArrays
#define glDepthFunc										__glDepthFunc
#define glDepthMask										__glDepthMask
#define glDepthRange									__glDepthRange
#define glDepthRangeArrayv								__glDepthRangeArrayv
#define glDepthRangeIndexed								__glDepthRangeIndexed
#define glDepthRangef									__glDepthRangef
#define glDetachShader									__glDetachShader
#define glDisable										__glDisable
#define glDisableVertexArrayAttrib						__glDisableVertexArrayAttrib
#define glDisableVertexAttribArray						__glDisableVertexAttribArray
#define glDisablei										__glDisablei
#define glDispatchCompute								__glDispatchCompute
#define glDispatchComputeIndirect						__glDispatchComputeIndirect
#define glDrawArrays									__glDrawArrays
#define glDrawArraysIndirect							__glDrawArraysIndirect
#define glDrawArraysInstanced							__glDrawArraysInstanced
#define glDrawArraysInstancedBaseInstance				__glDrawArraysInstancedBaseInstance
#define glDrawBuffer									__glDrawBuffer
#define glDrawBuffers									__glDrawBuffers
#define glDrawElements									__glDrawElements
#define glDrawElementsBaseVertex						__glDrawElementsBaseVertex
#define glDrawElementsIndirect							__glDrawElementsIndirect
#define glDrawElementsInstanced							__glDrawElementsInstanced
#define glDrawElementsInstancedBaseInstance				__glDrawElementsInstancedBaseInstance
#define glDrawElementsInstancedBaseVertex				__glDrawElementsInstancedBaseVertex
#define glDrawElementsInstancedBaseVertexBaseInstance	__glDrawElementsInstancedBaseVertexBaseInstance
#define glDrawRangeElements								__glDrawRangeElements
#define glDrawRangeElementsBaseVertex					__glDrawRangeElementsBaseVertex
#define glDrawTransformFeedback							__glDrawTransformFeedback
#define glDrawTransformFeedbackInstanced				__glDrawTransformFeedbackInstanced
#define glDrawTransformFeedbackStream					__glDrawTransformFeedbackStream
#define glDrawTransformFeedbackStreamInstanced			__glDrawTransformFeedbackStreamInstanced
#define glEnable										__glEnable
#define glEnableVertexArrayAttrib						__glEnableVertexArrayAttrib
#define glEnableVertexAttribArray						__glEnableVertexAttribArray
#define glEnablei										__glEnablei
#define glEndConditionalRender							__glEndConditionalRender
#define glEndQuery										__glEndQuery
#define glEndQueryIndexed								__glEndQueryIndexed
#define glEndTransformFeedback							__glEndTransformFeedback
#define glFenceSync										__glFenceSync
#define glFinish										__glFinish
#define glFlush											__glFlush
#define glFlushMappedBufferRange						__glFlushMappedBufferRange
#define glFlushMappedNamedBufferRange					__glFlushMappedNamedBufferRange
#define glFramebufferParameteri							__glFramebufferParameteri
#define glFramebufferParameteriMESA						__glFramebufferParameteriMESA
#define glFramebufferRenderbuffer						__glFramebufferRenderbuffer
#define glFramebufferTexture							__glFramebufferTexture
#define glFramebufferTexture1D							__glFramebufferTexture1D
#define glFramebufferTexture2D							__glFramebufferTexture2D
#define glFramebufferTexture3D							__glFramebufferTexture3D
#define glFramebufferTextureLayer						__glFramebufferTextureLayer
#define glFrontFace										__glFrontFace
#define glGenBuffers									__glGenBuffers
#define glGenFramebuffers								__glGenFramebuffers
#define glGenProgramPipelines							__glGenProgramPipelines
#define glGenQueries									__glGenQueries
#define glGenRenderbuffers								__glGenRenderbuffers
#define glGenSamplers									__glGenSamplers
#define glGenTextures									__glGenTextures
#define glGenTransformFeedbacks							__glGenTransformFeedbacks
#define glGenVertexArrays								__glGenVertexArrays
#define glGenerateMipmap								__glGenerateMipmap
#define glGenerateTextureMipmap							__glGenerateTextureMipmap
#define glGetActiveAtomicCounterBufferiv				__glGetActiveAtomicCounterBufferiv
#define glGetActiveAttrib								__glGetActiveAttrib
#define glGetActiveSubroutineName						__glGetActiveSubroutineName
#define glGetActiveSubroutineUniformName				__glGetActiveSubroutineUniformName
#define glGetActiveSubroutineUniformiv					__glGetActiveSubroutineUniformiv
#define glGetActiveUniform								__glGetActiveUniform
#define glGetActiveUniformBlockName						__glGetActiveUniformBlockName
#define glGetActiveUniformBlockiv						__glGetActiveUniformBlockiv
#define glGetActiveUniformName							__glGetActiveUniformName
#define glGetActiveUniformsiv							__glGetActiveUniformsiv
#define glGetAttachedShaders							__glGetAttachedShaders
#define glGetAttribLocation								__glGetAttribLocation
#define glGetBooleani_v									__glGetBooleani_v
#define glGetBooleanv									__glGetBooleanv
#define glGetBufferParameteri64v						__glGetBufferParameteri64v
#define glGetBufferParameteriv							__glGetBufferParameteriv
#define glGetBufferPointerv								__glGetBufferPointerv
#define glGetBufferSubData								__glGetBufferSubData
#define glGetCompressedTexImage							__glGetCompressedTexImage
#define glGetCompressedTextureImage						__glGetCompressedTextureImage
#define glGetCompressedTextureSubImage					__glGetCompressedTextureSubImage
#define glGetDebugMessageLog							__glGetDebugMessageLog
#define glGetDoublei_v									__glGetDoublei_v
#define glGetDoublev									__glGetDoublev
#define glGetError										__glGetError
#define glGetFloati_v									__glGetFloati_v
#define glGetFloatv										__glGetFloatv
#define glGetFragDataIndex								__glGetFragDataIndex
#define glGetFragDataLocation							__glGetFragDataLocation
#define glGetFramebufferAttachmentParameteriv			__glGetFramebufferAttachmentParameteriv
#define glGetFramebufferParameteriv						__glGetFramebufferParameteriv
#define glGetFramebufferParameterivMESA					__glGetFramebufferParameterivMESA
#define glGetGraphicsResetStatus						__glGetGraphicsResetStatus
#define glGetInteger64i_v								__glGetInteger64i_v
#define glGetInteger64v									__glGetInteger64v
#define glGetIntegeri_v									__glGetIntegeri_v
#define glGetIntegerv									__glGetIntegerv
#define glGetInternalformati64v							__glGetInternalformati64v
#define glGetInternalformativ							__glGetInternalformativ
#define glGetMultisamplefv								__glGetMultisamplefv
#define glGetNamedBufferParameteri64v					__glGetNamedBufferParameteri64v
#define glGetNamedBufferParameteriv						__glGetNamedBufferParameteriv
#define glGetNamedBufferPointerv						__glGetNamedBufferPointerv
#define glGetNamedBufferSubData							__glGetNamedBufferSubData
#define glGetNamedFramebufferAttachmentParameteriv		__glGetNamedFramebufferAttachmentParameteriv
#define glGetNamedFramebufferParameteriv				__glGetNamedFramebufferParameteriv
#define glGetNamedRenderbufferParameteriv				__glGetNamedRenderbufferParameteriv
#define glGetObjectLabel								__glGetObjectLabel
#define glGetObjectPtrLabel								__glGetObjectPtrLabel
#define glGetPointerv									__glGetPointerv
#define glGetProgramBinary								__glGetProgramBinary
#define glGetProgramInfoLog								__glGetProgramInfoLog
#define glGetProgramInterfaceiv							__glGetProgramInterfaceiv
#define glGetProgramPipelineInfoLog						__glGetProgramPipelineInfoLog
#define glGetProgramPipelineiv							__glGetProgramPipelineiv
#define glGetProgramResourceIndex						__glGetProgramResourceIndex
#define glGetProgramResourceLocation					__glGetProgramResourceLocation
#define glGetProgramResourceLocationIndex				__glGetProgramResourceLocationIndex
#define glGetProgramResourceName						__glGetProgramResourceName
#define glGetProgramResourceiv							__glGetProgramResourceiv
#define glGetProgramStageiv								__glGetProgramStageiv
#define glGetProgramiv									__glGetProgramiv
#define glGetQueryBufferObjecti64v						__glGetQueryBufferObjecti64v
#define glGetQueryBufferObjectiv						__glGetQueryBufferObjectiv
#define glGetQueryBufferObjectui64v						__glGetQueryBufferObjectui64v
#define glGetQueryBufferObjectuiv						__glGetQueryBufferObjectuiv
#define glGetQueryIndexediv								__glGetQueryIndexediv
#define glGetQueryObjecti64v							__glGetQueryObjecti64v
#define glGetQueryObjectiv								__glGetQueryObjectiv
#define glGetQueryObjectui64v							__glGetQueryObjectui64v
#define glGetQueryObjectuiv								__glGetQueryObjectuiv
#define glGetQueryiv									__glGetQueryiv
#define glGetRenderbufferParameteriv					__glGetRenderbufferParameteriv
#define glGetSamplerParameterIiv						__glGetSamplerParameterIiv
#define glGetSamplerParameterIuiv						__glGetSamplerParameterIuiv
#define glGetSamplerParameterfv							__glGetSamplerParameterfv
#define glGetSamplerParameteriv							__glGetSamplerParameteriv
#define glGetShaderInfoLog								__glGetShaderInfoLog
#define glGetShaderPrecisionFormat						__glGetShaderPrecisionFormat
#define glGetShaderSource								__glGetShaderSource
#define glGetShaderiv									__glGetShaderiv
#define glGetString										__glGetString
#define glGetStringi									__glGetStringi
#define glGetSubroutineIndex							__glGetSubroutineIndex
#define glGetSubroutineUniformLocation					__glGetSubroutineUniformLocation
#define glGetSynciv										__glGetSynciv
#define glGetTexImage									__glGetTexImage
#define glGetTexLevelParameterfv						__glGetTexLevelParameterfv
#define glGetTexLevelParameteriv						__glGetTexLevelParameteriv
#define glGetTexParameterIiv							__glGetTexParameterIiv
#define glGetTexParameterIuiv							__glGetTexParameterIuiv
#define glGetTexParameterfv								__glGetTexParameterfv
#define glGetTexParameteriv								__glGetTexParameteriv
#define glGetTextureImage								__glGetTextureImage
#define glGetTextureLevelParameterfv					__glGetTextureLevelParameterfv
#define glGetTextureLevelParameteriv					__glGetTextureLevelParameteriv
#define glGetTextureParameterIiv						__glGetTextureParameterIiv
#define glGetTextureParameterIuiv						__glGetTextureParameterIuiv
#define glGetTextureParameterfv							__glGetTextureParameterfv
#define glGetTextureParameteriv							__glGetTextureParameteriv
#define glGetTextureSubImage							__glGetTextureSubImage
#define glGetTransformFeedbackVarying					__glGetTransformFeedbackVarying
#define glGetTransformFeedbacki64_v						__glGetTransformFeedbacki64_v
#define glGetTransformFeedbacki_v						__glGetTransformFeedbacki_v
#define glGetTransformFeedbackiv						__glGetTransformFeedbackiv
#define glGetUniformBlockIndex							__glGetUniformBlockIndex
#define glGetUniformIndices								__glGetUniformIndices
#define glGetUniformLocation							__glGetUniformLocation
#define glGetUniformSubroutineuiv						__glGetUniformSubroutineuiv
#define glGetUniformdv									__glGetUniformdv
#define glGetUniformfv									__glGetUniformfv
#define glGetUniformiv									__glGetUniformiv
#define glGetUniformuiv									__glGetUniformuiv
#define glGetVertexArrayIndexed64iv						__glGetVertexArrayIndexed64iv
#define glGetVertexArrayIndexediv						__glGetVertexArrayIndexediv
#define glGetVertexArrayiv								__glGetVertexArrayiv
#define glGetVertexAttribIiv							__glGetVertexAttribIiv
#define glGetVertexAttribIuiv							__glGetVertexAttribIuiv
#define glGetVertexAttribLdv							__glGetVertexAttribLdv
#define glGetVertexAttribPointerv						__glGetVertexAttribPointerv
#define glGetVertexAttribdv								__glGetVertexAttribdv
#define glGetVertexAttribfv								__glGetVertexAttribfv
#define glGetVertexAttribiv								__glGetVertexAttribiv
#define glGetnCompressedTexImage						__glGetnCompressedTexImage
#define glGetnTexImage									__glGetnTexImage
#define glGetnUniformdv									__glGetnUniformdv
#define glGetnUniformfv									__glGetnUniformfv
#define glGetnUniformiv									__glGetnUniformiv
#define glGetnUniformuiv								__glGetnUniformuiv
#define glHint											__glHint
#define glInvalidateBufferData							__glInvalidateBufferData
#define glInvalidateBufferSubData						__glInvalidateBufferSubData
#define glInvalidateFramebuffer							__glInvalidateFramebuffer
#define glInvalidateNamedFramebufferData				__glInvalidateNamedFramebufferData
#define glInvalidateNamedFramebufferSubData				__glInvalidateNamedFramebufferSubData
#define glInvalidateSubFramebuffer						__glInvalidateSubFramebuffer
#define glInvalidateTexImage							__glInvalidateTexImage
#define glInvalidateTexSubImage							__glInvalidateTexSubImage
#define glIsBuffer										__glIsBuffer
#define glIsEnabled										__glIsEnabled
#define glIsEnabledi									__glIsEnabledi
#define glIsFramebuffer									__glIsFramebuffer
#define glIsProgram										__glIsProgram
#define glIsProgramPipeline								__glIsProgramPipeline
#define glIsQuery										__glIsQuery
#define glIsRenderbuffer								__glIsRenderbuffer
#define glIsSampler										__glIsSampler
#define glIsShader										__glIsShader
#define glIsSync										__glIsSync
#define glIsTexture										__glIsTexture
#define glIsTransformFeedback							__glIsTransformFeedback
#define glIsVertexArray									__glIsVertexArray
#define glLineWidth										__glLineWidth
#define glLinkProgram									__glLinkProgram
#define glLogicOp										__glLogicOp
#define glMapBuffer										__glMapBuffer
#define glMapBufferRange								__glMapBufferRange
#define glMapNamedBuffer								__glMapNamedBuffer
#define glMapNamedBufferRange							__glMapNamedBufferRange
#define glMemoryBarrier									__glMemoryBarrier
#define glMemoryBarrierByRegion							__glMemoryBarrierByRegion
#define glMinSampleShading								__glMinSampleShading
#define glMultiDrawArrays								__glMultiDrawArrays
#define glMultiDrawArraysIndirect						__glMultiDrawArraysIndirect
#define glMultiDrawArraysIndirectCount					__glMultiDrawArraysIndirectCount
#define glMultiDrawElements								__glMultiDrawElements
#define glMultiDrawElementsBaseVertex					__glMultiDrawElementsBaseVertex
#define glMultiDrawElementsIndirect						__glMultiDrawElementsIndirect
#define glMultiDrawElementsIndirectCount				__glMultiDrawElementsIndirectCount
#define glNamedBufferData								__glNamedBufferData
#define glNamedBufferStorage							__glNamedBufferStorage
#define glNamedBufferSubData							__glNamedBufferSubData
#define glNamedFramebufferDrawBuffer					__glNamedFramebufferDrawBuffer
#define glNamedFramebufferDrawBuffers					__glNamedFramebufferDrawBuffers
#define glNamedFramebufferParameteri					__glNamedFramebufferParameteri
#define glNamedFramebufferReadBuffer					__glNamedFramebufferReadBuffer
#define glNamedFramebufferRenderbuffer					__glNamedFramebufferRenderbuffer
#define glNamedFramebufferTexture						__glNamedFramebufferTexture
#define glNamedFramebufferTextureLayer					__glNamedFramebufferTextureLayer
#define glNamedRenderbufferStorage						__glNamedRenderbufferStorage
#define glNamedRenderbufferStorageMultisample			__glNamedRenderbufferStorageMultisample
#define glObjectLabel									__glObjectLabel
#define glObjectPtrLabel								__glObjectPtrLabel
#define glPatchParameterfv								__glPatchParameterfv
#define glPatchParameteri								__glPatchParameteri
#define glPauseTransformFeedback						__glPauseTransformFeedback
#define glPixelStoref									__glPixelStoref
#define glPixelStorei									__glPixelStorei
#define glPointParameterf								__glPointParameterf
#define glPointParameterfv								__glPointParameterfv
#define glPointParameteri								__glPointParameteri
#define glPointParameteriv								__glPointParameteriv
#define glPointSize										__glPointSize
#define glPolygonMode									__glPolygonMode
#define glPolygonOffset									__glPolygonOffset
#define glPolygonOffsetClamp							__glPolygonOffsetClamp
#define glPopDebugGroup									__glPopDebugGroup
#define glPrimitiveRestartIndex							__glPrimitiveRestartIndex
#define glProgramBinary									__glProgramBinary
#define glProgramParameteri								__glProgramParameteri
#define glProgramUniform1d								__glProgramUniform1d
#define glProgramUniform1dv								__glProgramUniform1dv
#define glProgramUniform1f								__glProgramUniform1f
#define glProgramUniform1fv								__glProgramUniform1fv
#define glProgramUniform1i								__glProgramUniform1i
#define glProgramUniform1iv								__glProgramUniform1iv
#define glProgramUniform1ui								__glProgramUniform1ui
#define glProgramUniform1uiv							__glProgramUniform1uiv
#define glProgramUniform2d								__glProgramUniform2d
#define glProgramUniform2dv								__glProgramUniform2dv
#define glProgramUniform2f								__glProgramUniform2f
#define glProgramUniform2fv								__glProgramUniform2fv
#define glProgramUniform2i								__glProgramUniform2i
#define glProgramUniform2iv								__glProgramUniform2iv
#define glProgramUniform2ui								__glProgramUniform2ui
#define glProgramUniform2uiv							__glProgramUniform2uiv
#define glProgramUniform3d								__glProgramUniform3d
#define glProgramUniform3dv								__glProgramUniform3dv
#define glProgramUniform3f								__glProgramUniform3f
#define glProgramUniform3fv								__glProgramUniform3fv
#define glProgramUniform3i								__glProgramUniform3i
#define glProgramUniform3iv								__glProgramUniform3iv
#define glProgramUniform3ui								__glProgramUniform3ui
#define glProgramUniform3uiv							__glProgramUniform3uiv
#define glProgramUniform4d								__glProgramUniform4d
#define glProgramUniform4dv								__glProgramUniform4dv
#define glProgramUniform4f								__glProgramUniform4f
#define glProgramUniform4fv								__glProgramUniform4fv
#define glProgramUniform4i								__glProgramUniform4i
#define glProgramUniform4iv								__glProgramUniform4iv
#define glProgramUniform4ui								__glProgramUniform4ui
#define glProgramUniform4uiv							__glProgramUniform4uiv
#define glProgramUniformMatrix2dv						__glProgramUniformMatrix2dv
#define glProgramUniformMatrix2fv						__glProgramUniformMatrix2fv
#define glProgramUniformMatrix2x3dv						__glProgramUniformMatrix2x3dv
#define glProgramUniformMatrix2x3fv						__glProgramUniformMatrix2x3fv
#define glProgramUniformMatrix2x4dv						__glProgramUniformMatrix2x4dv
#define glProgramUniformMatrix2x4fv						__glProgramUniformMatrix2x4fv
#define glProgramUniformMatrix3dv						__glProgramUniformMatrix3dv
#define glProgramUniformMatrix3fv						__glProgramUniformMatrix3fv
#define glProgramUniformMatrix3x2dv						__glProgramUniformMatrix3x2dv
#define glProgramUniformMatrix3x2fv						__glProgramUniformMatrix3x2fv
#define glProgramUniformMatrix3x4dv						__glProgramUniformMatrix3x4dv
#define glProgramUniformMatrix3x4fv						__glProgramUniformMatrix3x4fv
#define glProgramUniformMatrix4dv						__glProgramUniformMatrix4dv
#define glProgramUniformMatrix4fv						__glProgramUniformMatrix4fv
#define glProgramUniformMatrix4x2dv						__glProgramUniformMatrix4x2dv
#define glProgramUniformMatrix4x2fv						__glProgramUniformMatrix4x2fv
#define glProgramUniformMatrix4x3dv						__glProgramUniformMatrix4x3dv
#define glProgramUniformMatrix4x3fv						__glProgramUniformMatrix4x3fv
#define glProvokingVertex								__glProvokingVertex
#define glPushDebugGroup								__glPushDebugGroup
#define glQueryCounter									__glQueryCounter
#define glReadBuffer									__glReadBuffer
#define glReadPixels									__glReadPixels
#define glReadnPixels									__glReadnPixels
#define glReleaseShaderCompiler							__glReleaseShaderCompiler
#define glRenderbufferStorage							__glRenderbufferStorage
#define glRenderbufferStorageMultisample				__glRenderbufferStorageMultisample
#define glResumeTransformFeedback						__glResumeTransformFeedback
#define glSampleCoverage								__glSampleCoverage
#define glSampleMaski									__glSampleMaski
#define glSamplerParameterIiv							__glSamplerParameterIiv
#define glSamplerParameterIuiv							__glSamplerParameterIuiv
#define glSamplerParameterf								__glSamplerParameterf
#define glSamplerParameterfv							__glSamplerParameterfv
#define glSamplerParameteri								__glSamplerParameteri
#define glSamplerParameteriv							__glSamplerParameteriv
#define glScissor										__glScissor
#define glScissorArrayv									__glScissorArrayv
#define glScissorIndexed								__glScissorIndexed
#define glScissorIndexedv								__glScissorIndexedv
#define glShaderBinary									__glShaderBinary
#define glShaderSource									__glShaderSource
#define glShaderStorageBlockBinding						__glShaderStorageBlockBinding
#define glSpecializeShader								__glSpecializeShader
#define glStencilFunc									__glStencilFunc
#define glStencilFuncSeparate							__glStencilFuncSeparate
#define glStencilMask									__glStencilMask
#define glStencilMaskSeparate							__glStencilMaskSeparate
#define glStencilOp										__glStencilOp
#define glStencilOpSeparate								__glStencilOpSeparate
#define glTexBuffer										__glTexBuffer
#define glTexBufferRange								__glTexBufferRange
#define glTexImage1D									__glTexImage1D
#define glTexImage2D									__glTexImage2D
#define glTexImage2DMultisample							__glTexImage2DMultisample
#define glTexImage3D									__glTexImage3D
#define glTexImage3DMultisample							__glTexImage3DMultisample
#define glTexParameterIiv								__glTexParameterIiv
#define glTexParameterIuiv								__glTexParameterIuiv
#define glTexParameterf									__glTexParameterf
#define glTexParameterfv								__glTexParameterfv
#define glTexParameteri									__glTexParameteri
#define glTexParameteriv								__glTexParameteriv
#define glTexStorage1D									__glTexStorage1D
#define glTexStorage2D									__glTexStorage2D
#define glTexStorage2DMultisample						__glTexStorage2DMultisample
#define glTexStorage3D									__glTexStorage3D
#define glTexStorage3DMultisample						__glTexStorage3DMultisample
#define glTexSubImage1D									__glTexSubImage1D
#define glTexSubImage2D									__glTexSubImage2D
#define glTexSubImage3D									__glTexSubImage3D
#define glTextureBarrier								__glTextureBarrier
#define glTextureBuffer									__glTextureBuffer
#define glTextureBufferRange							__glTextureBufferRange
#define glTextureParameterIiv							__glTextureParameterIiv
#define glTextureParameterIuiv							__glTextureParameterIuiv
#define glTextureParameterf								__glTextureParameterf
#define glTextureParameterfv							__glTextureParameterfv
#define glTextureParameteri								__glTextureParameteri
#define glTextureParameteriv							__glTextureParameteriv
#define glTextureStorage1D								__glTextureStorage1D
#define glTextureStorage2D								__glTextureStorage2D
#define glTextureStorage2DMultisample					__glTextureStorage2DMultisample
#define glTextureStorage3D								__glTextureStorage3D
#define glTextureStorage3DMultisample					__glTextureStorage3DMultisample
#define glTextureSubImage1D								__glTextureSubImage1D
#define glTextureSubImage2D								__glTextureSubImage2D
#define glTextureSubImage3D								__glTextureSubImage3D
#define glTextureView									__glTextureView
#define glTransformFeedbackBufferBase					__glTransformFeedbackBufferBase
#define glTransformFeedbackBufferRange					__glTransformFeedbackBufferRange
#define glTransformFeedbackVaryings						__glTransformFeedbackVaryings
#define glUniform1d										__glUniform1d
#define glUniform1dv									__glUniform1dv
#define glUniform1f										__glUniform1f
#define glUniform1fv									__glUniform1fv
#define glUniform1i										__glUniform1i
#define glUniform1iv									__glUniform1iv
#define glUniform1ui									__glUniform1ui
#define glUniform1uiv									__glUniform1uiv
#define glUniform2d										__glUniform2d
#define glUniform2dv									__glUniform2dv
#define glUniform2f										__glUniform2f
#define glUniform2fv									__glUniform2fv
#define glUniform2i										__glUniform2i
#define glUniform2iv									__glUniform2iv
#define glUniform2ui									__glUniform2ui
#define glUniform2uiv									__glUniform2uiv
#define glUniform3d										__glUniform3d
#define glUniform3dv									__glUniform3dv
#define glUniform3f										__glUniform3f
#define glUniform3fv									__glUniform3fv
#define glUniform3i										__glUniform3i
#define glUniform3iv									__glUniform3iv
#define glUniform3ui									__glUniform3ui
#define glUniform3uiv									__glUniform3uiv
#define glUniform4d										__glUniform4d
#define glUniform4dv									__glUniform4dv
#define glUniform4f										__glUniform4f
#define glUniform4fv									__glUniform4fv
#define glUniform4i										__glUniform4i
#define glUniform4iv									__glUniform4iv
#define glUniform4ui									__glUniform4ui
#define glUniform4uiv									__glUniform4uiv
#define glUniformBlockBinding							__glUniformBlockBinding
#define glUniformMatrix2dv								__glUniformMatrix2dv
#define glUniformMatrix2fv								__glUniformMatrix2fv
#define glUniformMatrix2x3dv							__glUniformMatrix2x3dv
#define glUniformMatrix2x3fv							__glUniformMatrix2x3fv
#define glUniformMatrix2x4dv							__glUniformMatrix2x4dv
#define glUniformMatrix2x4fv							__glUniformMatrix2x4fv
#define glUniformMatrix3dv								__glUniformMatrix3dv
#define glUniformMatrix3fv								__glUniformMatrix3fv
#define glUniformMatrix3x2dv							__glUniformMatrix3x2dv
#define glUniformMatrix3x2fv							__glUniformMatrix3x2fv
#define glUniformMatrix3x4dv							__glUniformMatrix3x4dv
#define glUniformMatrix3x4fv							__glUniformMatrix3x4fv
#define glUniformMatrix4dv								__glUniformMatrix4dv
#define glUniformMatrix4fv								__glUniformMatrix4fv
#define glUniformMatrix4x2dv							__glUniformMatrix4x2dv
#define glUniformMatrix4x2fv							__glUniformMatrix4x2fv
#define glUniformMatrix4x3dv							__glUniformMatrix4x3dv
#define glUniformMatrix4x3fv							__glUniformMatrix4x3fv
#define glUniformSubroutinesuiv							__glUniformSubroutinesuiv
#define glUnmapBuffer									__glUnmapBuffer
#define glUnmapNamedBuffer								__glUnmapNamedBuffer
#define glUseProgram									__glUseProgram
#define glUseProgramStages								__glUseProgramStages
#define glValidateProgram								__glValidateProgram
#define glValidateProgramPipeline						__glValidateProgramPipeline
#define glVertexArrayAttribBinding						__glVertexArrayAttribBinding
#define glVertexArrayAttribFormat						__glVertexArrayAttribFormat
#define glVertexArrayAttribIFormat						__glVertexArrayAttribIFormat
#define glVertexArrayAttribLFormat						__glVertexArrayAttribLFormat
#define glVertexArrayBindingDivisor						__glVertexArrayBindingDivisor
#define glVertexArrayElementBuffer						__glVertexArrayElementBuffer
#define glVertexArrayVertexBuffer						__glVertexArrayVertexBuffer
#define glVertexArrayVertexBuffers						__glVertexArrayVertexBuffers
#define glVertexAttrib1d								__glVertexAttrib1d
#define glVertexAttrib1dv								__glVertexAttrib1dv
#define glVertexAttrib1f								__glVertexAttrib1f
#define glVertexAttrib1fv								__glVertexAttrib1fv
#define glVertexAttrib1s								__glVertexAttrib1s
#define glVertexAttrib1sv								__glVertexAttrib1sv
#define glVertexAttrib2d								__glVertexAttrib2d
#define glVertexAttrib2dv								__glVertexAttrib2dv
#define glVertexAttrib2f								__glVertexAttrib2f
#define glVertexAttrib2fv								__glVertexAttrib2fv
#define glVertexAttrib2s								__glVertexAttrib2s
#define glVertexAttrib2sv								__glVertexAttrib2sv
#define glVertexAttrib3d								__glVertexAttrib3d
#define glVertexAttrib3dv								__glVertexAttrib3dv
#define glVertexAttrib3f								__glVertexAttrib3f
#define glVertexAttrib3fv								__glVertexAttrib3fv
#define glVertexAttrib3s								__glVertexAttrib3s
#define glVertexAttrib3sv								__glVertexAttrib3sv
#define glVertexAttrib4Nbv								__glVertexAttrib4Nbv
#define glVertexAttrib4Niv								__glVertexAttrib4Niv
#define glVertexAttrib4Nsv								__glVertexAttrib4Nsv
#define glVertexAttrib4Nub								__glVertexAttrib4Nub
#define glVertexAttrib4Nubv								__glVertexAttrib4Nubv
#define glVertexAttrib4Nuiv								__glVertexAttrib4Nuiv
#define glVertexAttrib4Nusv								__glVertexAttrib4Nusv
#define glVertexAttrib4bv								__glVertexAttrib4bv
#define glVertexAttrib4d								__glVertexAttrib4d
#define glVertexAttrib4dv								__glVertexAttrib4dv
#define glVertexAttrib4f								__glVertexAttrib4f
#define glVertexAttrib4fv								__glVertexAttrib4fv
#define glVertexAttrib4iv								__glVertexAttrib4iv
#define glVertexAttrib4s								__glVertexAttrib4s
#define glVertexAttrib4sv								__glVertexAttrib4sv
#define glVertexAttrib4ubv								__glVertexAttrib4ubv
#define glVertexAttrib4uiv								__glVertexAttrib4uiv
#define glVertexAttrib4usv								__glVertexAttrib4usv
#define glVertexAttribBinding							__glVertexAttribBinding
#define glVertexAttribDivisor							__glVertexAttribDivisor
#define glVertexAttribFormat							__glVertexAttribFormat
#define glVertexAttribI1i								__glVertexAttribI1i
#define glVertexAttribI1iv								__glVertexAttribI1iv
#define glVertexAttribI1ui								__glVertexAttribI1ui
#define glVertexAttribI1uiv								__glVertexAttribI1uiv
#define glVertexAttribI2i								__glVertexAttribI2i
#define glVertexAttribI2iv								__glVertexAttribI2iv
#define glVertexAttribI2ui								__glVertexAttribI2ui
#define glVertexAttribI2uiv								__glVertexAttribI2uiv
#define glVertexAttribI3i								__glVertexAttribI3i
#define glVertexAttribI3iv								__glVertexAttribI3iv
#define glVertexAttribI3ui								__glVertexAttribI3ui
#define glVertexAttribI3uiv								__glVertexAttribI3uiv
#define glVertexAttribI4bv								__glVertexAttribI4bv
#define glVertexAttribI4i								__glVertexAttribI4i
#define glVertexAttribI4iv								__glVertexAttribI4iv
#define glVertexAttribI4sv								__glVertexAttribI4sv
#define glVertexAttribI4ubv								__glVertexAttribI4ubv
#define glVertexAttribI4ui								__glVertexAttribI4ui
#define glVertexAttribI4uiv								__glVertexAttribI4uiv
#define glVertexAttribI4usv								__glVertexAttribI4usv
#define glVertexAttribIFormat							__glVertexAttribIFormat
#define glVertexAttribIPointer							__glVertexAttribIPointer
#define glVertexAttribL1d								__glVertexAttribL1d
#define glVertexAttribL1dv								__glVertexAttribL1dv
#define glVertexAttribL2d								__glVertexAttribL2d
#define glVertexAttribL2dv								__glVertexAttribL2dv
#define glVertexAttribL3d								__glVertexAttribL3d
#define glVertexAttribL3dv								__glVertexAttribL3dv
#define glVertexAttribL4d								__glVertexAttribL4d
#define glVertexAttribL4dv								__glVertexAttribL4dv
#define glVertexAttribLFormat							__glVertexAttribLFormat
#define glVertexAttribLPointer							__glVertexAttribLPointer
#define glVertexAttribP1ui								__glVertexAttribP1ui
#define glVertexAttribP1uiv								__glVertexAttribP1uiv
#define glVertexAttribP2ui								__glVertexAttribP2ui
#define glVertexAttribP2uiv								__glVertexAttribP2uiv
#define glVertexAttribP3ui								__glVertexAttribP3ui
#define glVertexAttribP3uiv								__glVertexAttribP3uiv
#define glVertexAttribP4ui								__glVertexAttribP4ui
#define glVertexAttribP4uiv								__glVertexAttribP4uiv
#define glVertexAttribPointer							__glVertexAttribPointer
#define glVertexBindingDivisor							__glVertexBindingDivisor
#define glViewport										__glViewport
#define glViewportArrayv								__glViewportArrayv
#define glViewportIndexedf								__glViewportIndexedf
#define glViewportIndexedfv								__glViewportIndexedfv
#define glWaitSync										__glWaitSync
